# Introduction to Tensors

In [1]:
import torch

## Creating Tensors:

### Escalares:

Para crear escalares utiliza el método `torch.tensor()` -> https://pytorch.org/docs/stable/tensors.html

In [2]:
escalar = torch.tensor(7)
escalar

tensor(7)

El método `.ndim` declara las dimensiones de nuestro tensor:

In [3]:
escalar.ndim

0

Y `.item()` devuelve el tensor en forma de int para python

In [4]:
escalar.item()

7

### Vectores:

Para crear vectores se utiliza el mismo método:

In [5]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

Este vector es un objeto 1x2, por ende los outputs de los métodos `.ndim` y `.shape`

### Matrices:

Para una matriz:

In [8]:
MATRIZ = torch.tensor([[7, 8],
                       [9, 10]])
MATRIZ

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIZ.ndim

2

In [10]:
MATRIZ.shape

torch.Size([2, 2])

Es una matriz de 2x2 como sugiere `.shape`

In [11]:
MATRIZ[0]

tensor([7, 8])

In [12]:
MATRIZ[0][1]

tensor(8)

### Tensores 3D:

In [13]:
TN = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TN

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TN[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
TN.ndim

3

In [15]:
TN.shape

torch.Size([1, 3, 3])

Al utilizar `.shape` en el output se representa el tamaño del tensor.
 
El 1 refiere a la profundidad del tensor, el primer 3 refiere al número de filas y el último 3 refiere al número de columnas.

## Nomenclatura:

Al trabajar con este tipo de objetos, se recomienda usar nombres de variables en lowercase para escalares y vectores, mientras que se usan nombres de variables en UPPERCASE para matrices y tensores de 3D en adelante