# Random Tensors

## Creating Random Tensors

La forma en la que distintas redes neuronales aprenden es haciendo uso inicialmente de tensores aleatorios y después se ajustan para representar mejor nuestros datos

`start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Revisar la documentación: https://pytorch.org/docs/main/generated/torch.rand.html

In [1]:
import torch

Para crear un tensor aleatorio con shape (3,4):

In [6]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0364, 0.5946, 0.2637, 0.2536],
        [0.7535, 0.1239, 0.6240, 0.9600],
        [0.7258, 0.9420, 0.0466, 0.3263]])

In [7]:
random_tensor.shape

torch.Size([3, 4])

In [8]:
random_tensor.ndim

2

In [10]:
random_tensor = torch.rand(2, 3, 4)
random_tensor

tensor([[[0.5265, 0.0424, 0.3317, 0.6158],
         [0.3329, 0.6538, 0.0888, 0.0811],
         [0.3583, 0.4195, 0.2368, 0.9885]],

        [[0.1634, 0.4401, 0.4638, 0.5149],
         [0.8650, 0.3834, 0.7138, 0.7989],
         [0.3430, 0.7125, 0.8019, 0.2639]]])

In [11]:
random_tensor.shape

torch.Size([2, 3, 4])

In [12]:
random_tensor.ndim

3

Crear un tensor aleatorio con shape similar a un tensor de imagen:

In [15]:
image_tensor = torch.rand(size=(3, 224, 224))
image_tensor

tensor([[[0.5146, 0.5774, 0.0059,  ..., 0.4453, 0.6688, 0.5231],
         [0.2084, 0.8142, 0.7552,  ..., 0.3150, 0.0884, 0.4466],
         [0.9830, 0.4559, 0.7450,  ..., 0.1888, 0.2285, 0.1813],
         ...,
         [0.0032, 0.0564, 0.5463,  ..., 0.7069, 0.2963, 0.7814],
         [0.4524, 0.1253, 0.2597,  ..., 0.2904, 0.0360, 0.5190],
         [0.0573, 0.2285, 0.9520,  ..., 0.4947, 0.0350, 0.7248]],

        [[0.0916, 0.7761, 0.1391,  ..., 0.3670, 0.8832, 0.0300],
         [0.7675, 0.6408, 0.4578,  ..., 0.4676, 0.6463, 0.9195],
         [0.6617, 0.1854, 0.0878,  ..., 0.9723, 0.1388, 0.8550],
         ...,
         [0.6705, 0.0768, 0.2157,  ..., 0.7468, 0.9121, 0.2903],
         [0.4969, 0.6513, 0.1538,  ..., 0.3782, 0.4859, 0.8664],
         [0.3758, 0.3748, 0.2709,  ..., 0.6041, 0.9686, 0.4847]],

        [[0.7233, 0.2766, 0.3589,  ..., 0.1472, 0.7523, 0.7635],
         [0.7742, 0.3061, 0.6259,  ..., 0.8184, 0.9584, 0.7143],
         [0.2324, 0.2754, 0.0585,  ..., 0.7955, 0.1006, 0.

Donde dentro de size se declara height, width y colour channels (R, G, B) para representar la imagen

In [16]:
image_tensor.shape, image_tensor.ndim

(torch.Size([3, 224, 224]), 3)

Donde se tiene 3 canales de color, 224 en altura y 224 en ancho de la imagen

Cabe mencionar que al declarar un tensor aleatorio con el uso de `torch.rand(size=(1, 3, 3))` es igual que sin usar el parámetro `size` como `torch.rand(1, 3, 3)`

## Creating Null Tensors

Para crear tensores nulos se puede utilizar `torch.zeros()` como se ve a continuación

In [17]:
ceros = torch.zeros(3,4)
ceros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ceros * random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
ceros * random_tensor[0]

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Los tensores nulos son útiles para transformaciones de tensores

Para crear tensores de puros 1 se utiliza `torch.ones()`

In [23]:
unos = torch.ones(3, 4)
unos

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
unos.dtype

torch.float32

El atributo `.dtype` muestra el tipo de datos por defecto de nuestro objeto

Por defecto, cada que se crea un tensor usando pytorch, el tipo de datos de nuestro tensor es `torch.float32`

Es más común el uso de tensores nulos que de 1s pero es importante recordar ambos