# Range Tensors

In [1]:
import torch

## Creating a range of tensors

Para versiones antiguas de PyTorch, se utiliza `torch.range()` crear un rango de tensores.

In [2]:
torch.range(0, 10)

/tmp/ipykernel_15534/1549641488.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

Sin embargo, esta función será deprecada, por lo tanto, ahora se utilizará `torch.arange()`donde se crea un rango con los intervalos [ini, fin)

Revisar la documentación oficial: https://pytorch.org/docs/stable/generated/torch.arange.html

In [3]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

## Creating tensor-like:

Un tensor-like es una forma de crear tensores con un shape ya definida sin tener que especificarla. Esto se hace a través de otro tensor ya definido con el mismo shape que queremos

In [7]:
uno_al_diez = torch.arange(1, 11)
uno_al_diez

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Una vez ya definido el tensor con el shape a replicar se utiliza `torch.zeros_like()` en el caso de querer un vector de ceros

In [8]:
diez_ceros = torch.zeros_like(uno_al_diez)
diez_ceros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Para hacer un vector de unos usamos `torch.ones_like()`

In [9]:
diez_unos = torch.ones_like(uno_al_diez)
diez_unos

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])