# Tensor Data Types

In [1]:
import torch

## Datatypes de tensores:

El tipo de dato en objetos de pytorch por defecto es `torch.float32`, incluso si se especifica como `None`

In [6]:
tn = torch.tensor([3.0, 6.0, 9.0], dtype=None)
tn

tensor([3., 6., 9.])

In [7]:
tn.dtype

torch.float32

Podemos especificar otro tipo de datos para nuestro tensor:

In [8]:
tn = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
tn

tensor([3., 6., 9.], dtype=torch.float16)

In [9]:
tn.dtype

torch.float16

Para revisar los tipos de datos válidos de `torch.tensor()` hay que revisar la documentación: https://pytorch.org/docs/stable/tensors.html

Al crear tensores usando `torch.tensor()` los parámetros más importantes son: 

1) `dtype` <- especificar tipo de datos
2) `device` <- en donde correrá el código (CPU, GPU o TPU)
3) `requires_grad` <- trackear gradientes del tensor al realizarle operaciones

`device` por defecto está declarado en el cpu pero puede modificarse de la siguiente forma:

1) `device = "cpu"`
2) `device = "cuda"`

**Nota:** El datatype de tensores es generador de 1 de los 3 más comunes erroes cometidos en PyTorch y DL.

1) Datatype erroneo del tensor
2) Shape erroneo del tensor
3) Tensores en el device erroneo

In [11]:
float32_tensor = torch.tensor([3.0, 6.0, 9.0])

float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [12]:
float32_tensor.dtype, float16_tensor.dtype

(torch.float32, torch.float16)

Al multiplicar tensores con distinta precisión de datos, si el dtype es congruente se obtiene lo siguiente:

In [14]:
(float16_tensor * float32_tensor).dtype

torch.float32

## Atributos de tensores:

Para obtener información de tensores se hace de la siguiente forma

1) Para datatype -> `.dtype`
2) Para tamaño -> `.shape` o `.size()`
3) Para device -> `.device`

Crearemos algunos tensores para probar estos atributos:

In [15]:
tn = torch.rand(3, 4)
tn

tensor([[0.2052, 0.7446, 0.4763, 0.8558],
        [0.5012, 0.5384, 0.6188, 0.0703],
        [0.9162, 0.7690, 0.1519, 0.1051]])

In [16]:
tn.dtype

torch.float32

In [17]:
tn.shape

torch.Size([3, 4])

In [19]:
tn.size()

torch.Size([3, 4])

In [18]:
tn.device

device(type='cpu')