# Tensor Operations

Algunas de las operaciones de tensores que podemos realizar son:

1. Suma y resta
2. Multiplicación por elemento
3. División
4. Multiplicación de matrices

Las redes neuronales utiliza estas operaciones para aprender de los datos

In [1]:
import torch

## Operaciones con Escalares

Las operaciones de un tensor con un escalar se realiza de la misma forma que tipos de datos primitivos:

In [2]:
tn = torch.tensor([1, 2, 3])
tn + 100

tensor([101, 102, 103])

In [3]:
tn - 10

tensor([-9, -8, -7])

In [4]:
tn * 5

tensor([ 5, 10, 15])

In [5]:
tn / 2

tensor([0.5000, 1.0000, 1.5000])

## Producto Hadamard

El producto Hadamard (también conocido como: producto elemento a elemento, componente a componente o punto a punto) es una operacion matricial para **matrices de las mismas dimensiones**, donde se multiplican los elementos de las mismas posiciones en cada matriz.

Sea A  = [2, 3, 4] y B = [5, 6 ,7] el producto Hadamard será de la siguiente forma:

[2x5, 3x6, 4x7] = [10, 18, 28]

Para calcular el producto Hadamard de 2 tensores A y B se utiliza: `A * B`

In [6]:
a_tn = torch.tensor([2, 3, 4])
b_tn = torch.tensor([5, 6, 7])

a_tn * b_tn

tensor([10, 18, 28])

In [7]:
c_tn = torch.tensor([[1, 2],
                     [3, 4]])

d_tn = torch.tensor([[5, 6], 
                     [7, 8]])

c_tn * d_tn

tensor([[ 5, 12],
        [21, 32]])

## Producto Punto (Escalar)

Para el producto escalar o producto punto se utiliza el método `torch.matmul()`

Para ser válido el producto escalar, los tensores tienen que ser de la forma:

A [=] m x n

B [=] n x p

De modo que el resultado será un tensor C [=] m x p

In [8]:
torch.matmul(a_tn, b_tn)

tensor(56)

In [9]:
torch.matmul(c_tn, d_tn)

tensor([[19, 22],
        [43, 50]])

También se puede usar la notación `A @ B`

In [10]:
a_tn @ b_tn

tensor(56)

In [11]:
c_tn @ d_tn

tensor([[19, 22],
        [43, 50]])

Si existe un método dentro de la librería para realizar una operación es recomendable usarlo en lugar de realizarlo a mano.

Debido a que, en la mayoría de los casos, estos métodos ya están optimizados por lo que serán más eficientes

Comparativa de eficiencia:

In [12]:
%%time
value = 0
for i in range(len(a_tn)):
    value += a_tn[i] * b_tn[i]
value

CPU times: user 2.15 ms, sys: 219 μs, total: 2.37 ms
Wall time: 1.64 ms


tensor(56)

In [13]:
%%time
torch.matmul(a_tn, b_tn)

CPU times: user 199 μs, sys: 21 μs, total: 220 μs
Wall time: 158 μs


tensor(56)

In [14]:
%%time
a_tn @ b_tn

CPU times: user 318 μs, sys: 0 ns, total: 318 μs
Wall time: 271 μs


tensor(56)

Evidentemente, es mucho más eficiente el método implementado en la librería de PyTorch. 

Al incrementar la cantidad de datos, esta diferencia incrementará de forma muy notable

No obstante, a pesar de que la notación para el producto escalar `@` no es tan legible o común, muestra una mayor eficiencia. Pero no la suficiente para sacrificar la legibilidad del código

Otra forma de realizar la operación es con el método `torch.mm()`

In [15]:
torch.mm(a_tn, b_tn)

RuntimeError: self must be a matrix

Sin embargo, este método no se puede realizar sobre vectores, debe tener por lo menos las dimensiones de una matriz para ser válido

In [16]:
torch.mm(c_tn, d_tn)

tensor([[19, 22],
        [43, 50]])

## Transpuesta

Para realizar la operación transpuesta sobre un tensor, podemos usar `.T` sobre nuestro tensor

Por ejemplo:

In [17]:
a_tn = torch.rand(2, 3)
a_tn

tensor([[0.5023, 0.1414, 0.3671],
        [0.9278, 0.4323, 0.9041]])

In [18]:
b_tn = torch.rand(2, 3)
b_tn

tensor([[0.4912, 0.0293, 0.2706],
        [0.8820, 0.1518, 0.5470]])

In [19]:
torch.matmul(a_tn, b_tn)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x3 and 2x3)

Debido a que no se cumplen las dimensiones válidas para el producto punto, podemos arreglarlo usando la transpuesta de alguno de los tensores

In [20]:
b_tn.T

tensor([[0.4912, 0.8820],
        [0.0293, 0.1518],
        [0.2706, 0.5470]])

In [21]:
b_tn.shape, b_tn.T.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [22]:
torch.matmul(a_tn, b_tn.T)

tensor([[0.3502, 0.6653],
        [0.7131, 1.3785]])

In [23]:
torch.matmul(a_tn, b_tn.T).shape

torch.Size([2, 2])

## Mínimo de un Tensor:

Para un tensor A, podemos utilizar `torch.min(A)` o `A.min()`

In [24]:
tn = torch.arange(10, 101, 10)
tn

tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [25]:
torch.min(tn)

tensor(10)

In [26]:
tn.min()

tensor(10)

## Máximo de un Tensor:

Para un tensor A, podemos utilizar `torch.max(A)` o `A.max()`

In [27]:
torch.max(tn)

tensor(100)

In [28]:
tn.max()

tensor(100)

## Promedio de un Tensor:

Para calcular el promedio de los elementos de nuestro tensor A, podemos utilizar `torch.mean(A)` o `A.mean()`

Sin embargo, es necesario que el tipo de dato de nuestro tensor sea `float` o un dtype complejo

Revisar la documentación: https://pytorch.org/docs/stable/generated/torch.mean.html

In [29]:
torch.mean(tn)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [30]:
tn.dtype

torch.int64

Podemos cambiar el tipo de datos de un tensor A con el método `A.type()` y como parámetro pasar el tipo de dato deseado, en este caso `torch.float32`

In [31]:
torch.mean(tn.type(torch.float32))

tensor(55.)

In [32]:
tn.type(torch.float32).mean()

tensor(55.)

## Suma de los Elementos de un Tensor:

Para un tensor A, podemos usar `torch.sum(A)` o `A.sum()`

In [33]:
torch.sum(tn)

tensor(550)

In [34]:
tn.sum()

tensor(550)

## Posición del Mínimo y Máximo en un Tensor

Para encontrar la posición del mínimo en el tensor A utilizamos: `A.argmin()`

In [35]:
tn.argmin()

tensor(0)

In [36]:
tn[0]

tensor(10)

Para el máximo se usa: `A.argmax()`

In [37]:
tn.argmax()

tensor(9)

In [38]:
tn[9]

tensor(100)