# Advanced Tensor Operations

In [1]:
import torch

Las operaciones que veremos a continuación son:

1. Reshape: 

Redimensiona un tensor input a una forma deseada.


2. View: 

Regresa una vista de un tensor input de ciertas dimensiones usando la misma memoria en el tensor original.

3. Stacking: 

Combina múltiples tensores uno encima de otro (vstack) o lado a lado (hstack).

Leer la documentación: https://pytorch.org/docs/main/generated/torch.stack.html

4. Squeeze:

Elimina todas las dimensiones singulares de un tensor.

5. Unsqueeze:

Añade una dimensión `1` a nuestro tensor objetivo.

6. Permute:

Regresa un vista del tensor input con dimensiones permutadas (cambiadas) de cierta forma.

## Reshaping Tensors

Para un tensor A, la operación `A.reshape(a, b)` redimensiona el tensor a la forma a x b con el propósito de evitar problemas de dimensiones en las otras operaciones

La estructura elegida a,b debe ser coherente con la cantidad de datos del tensor original

In [2]:
x = torch.arange(0., 10.)
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [3]:
x.dtype

torch.float32

In [4]:
x.shape

torch.Size([10])

En este ejemplo, al invocar la función sin cambiar la estructura original (10 elementos en 1 dimensión), la función añade otra dimensión al tensor original

In [5]:
x.reshape(1, 10)

tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])

Comparativa de dimensiones:

In [6]:
x.shape, x.reshape(1,10).shape

(torch.Size([10]), torch.Size([1, 10]))

Cabe mencionar que esto no reescribirá el tensor original, por lo que para que se vean reflejados los cambios hay que guardarlos

In [7]:
x

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Podemos redimensionar los elementos de otra forma que sea coherente con la cantidad de datos. A continuación se verá otro ejemplo:

In [8]:
x.reshape(2, 5)

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

Comparando el original con el redimensionado:

In [9]:
x.shape, x.reshape(2, 5).shape

(torch.Size([10]), torch.Size([2, 5]))

Finalmente, veremos un ejemplo más drastico:

In [10]:
x.reshape(10, 1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [11]:
x.shape, x.reshape(10, 1).shape

(torch.Size([10]), torch.Size([10, 1]))

## View Tensors

El método `A.view(a, b)` nos permite visualizar un tensor usando otras dimensiones

Cabe mencionar que al usar este método, la memoria se comparte

In [12]:
x = torch.arange(0, 10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
z = x.view(5, 2)
z

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

Si modificamos z, también se modificará x

In [14]:
z[0][0] = 5
z, x

(tensor([[5, 1],
         [2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]),
 tensor([5, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

## Stack Tensors

El método `torch.stack()` concatena secuencias de tensores en nuevas dimensiones. Para ello, todos deben tener las mismas dimensiones

Para esta función los parámetros dados son:

1. `tensors`: 

Lista o tupla de tensores del mismo tamaño

2. `dim`: 

Especifíca el índice de la nueva dimensión en la que los tensores serán concatenados.

La nueva dimensión especificada por `dim` debe ser un índice válido, es decir, debe estar en el rango de [-D+1, D+1], donde D es el número de dimensiones de los tensores

Cada dimensión adicional representa un nuevo eje de datos

Leer la documentación: https://pytorch.org/docs/main/generated/torch.stack.html

A continuación veremos algunos ejemplos:

1) Vectores a Matriz:

Sean 2 vectores, éstos son tensores 1D:

In [15]:
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

vector1.shape, vector2.shape

(torch.Size([3]), torch.Size([3]))


$$\mathbf{v_1} = \begin{pmatrix} 1 \\ 2 \\ 3 \end{pmatrix}$$

$$\mathbf{v_2} = \begin{pmatrix} 4 \\ 5 \\ 6 \end{pmatrix}$$

* stack con `dim = 0`

In [16]:
torch.stack([vector1, vector2], dim = 0)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
torch.stack([vector1, vector2], dim = 0).shape

torch.Size([2, 3])

$$\begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

Se crea una matriz con los vectores originales, donde cada vector es una fila

* stack con `dim = 1`

In [18]:
torch.stack([vector1, vector2], dim = 1)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [19]:
torch.stack([vector1, vector2], dim = 1).shape

torch.Size([3, 2])

$$\begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}$$

Alternativamente, de esta forma se crea una matriz con los vectores donde cada uno es una columna

2) Matriz a Tensor 3D

Si tenemos 2 matrices (tensores de orden 2):

In [20]:
matriz1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

matriz2 = torch.tensor([[7, 8, 9],
                        [10, 11, 12]])

matriz1.shape, matriz2.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

$$\mathbf{M_1} = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

$$\mathbf{M_2} = \begin{bmatrix} 7 & 8 & 9 \\ 10 & 11 & 12 \end{bmatrix}$$

* stack con `dim = 0`

In [21]:
torch.stack([matriz1, matriz2], dim=0)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [22]:
torch.stack([matriz1, matriz2], dim=0).shape

torch.Size([2, 2, 3])

Se crea un tensor 3D donde la primera matriz se encuentra enfrente y la 2da matriz se encuentra atrás de la primera, haciendo uso de la profundidad del tensor

* stack con `dim = 1`

In [23]:
torch.stack([matriz1, matriz2], dim=1)

tensor([[[ 1,  2,  3],
         [ 7,  8,  9]],

        [[ 4,  5,  6],
         [10, 11, 12]]])

In [24]:
torch.stack([matriz1, matriz2], dim=1).shape

torch.Size([2, 2, 3])

En este caso, en la primera capa del tensor se reparten los elementos de la primera fila de cada matriz; siendo la primera fila de esta capa los elementos de la primera fila de la primera matriz y la segunda fila de la capa los elementos de la primera fila de la segunda matriz

* stack con `dim = 2`

In [25]:
torch.stack([matriz1, matriz2], dim=2)

tensor([[[ 1,  7],
         [ 2,  8],
         [ 3,  9]],

        [[ 4, 10],
         [ 5, 11],
         [ 6, 12]]])

In [26]:
torch.stack([matriz1, matriz2], dim=2).shape

torch.Size([2, 3, 2])

Para este caso, la primera capa contiene las primeras filas de cada matriz pero las convierte en columnas y la segunda capa del tensor contiene las segundas filas de cada matriz convertidas en columnas

3) Tensor 3D a 4D

Teniendo 2 tensores 3D:

In [27]:
tensor1 = torch.tensor([[[1, 2], 
                         [3, 4]], 

                        [[5, 6], 
                         [7, 8]]])

tensor2 = torch.tensor([[[9, 10], 
                         [11, 12]], 

                        [[13, 14], 
                         [15, 16]]])

tensor1.shape, tensor2.shape

(torch.Size([2, 2, 2]), torch.Size([2, 2, 2]))

* stack con `dim = 0`

In [28]:
torch.stack((tensor1, tensor2), dim = 0)

tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]])

In [29]:
torch.stack((tensor1, tensor2), dim = 0).shape

torch.Size([2, 2, 2, 2])

De esta forma se crea un tensor 4D donde en la 4ta dimensión o capa se tiene a cada uno de los tensores 3D

* stack con `dim = 1`

In [30]:
torch.stack((tensor1, tensor2), dim = 1)

tensor([[[[ 1,  2],
          [ 3,  4]],

         [[ 9, 10],
          [11, 12]]],


        [[[ 5,  6],
          [ 7,  8]],

         [[13, 14],
          [15, 16]]]])

In [31]:
torch.stack((tensor1, tensor2), dim = 1).shape

torch.Size([2, 2, 2, 2])

Intercambia los elementos dentro de la 2da capa de profundidad del primer tensor 3D con los elementos de la 1ra capa de produndidad del segundo tensor 3D; los cuales están contenidos en distintas capas 4D del tensor 4D. 

De tal forma que:

[[9, 10], [11, 12]] están detrás de la capa [[1, 2], [3, 4]]

Mientras que:

[[5, 6], [7, 8]] están adelante de la capa [[13, 14], [15, 16]]

* stack con `dim = 2`

In [32]:
torch.stack((tensor1, tensor2), dim = 2)

tensor([[[[ 1,  2],
          [ 9, 10]],

         [[ 3,  4],
          [11, 12]]],


        [[[ 5,  6],
          [13, 14]],

         [[ 7,  8],
          [15, 16]]]])

In [33]:
torch.stack((tensor1, tensor2), dim = 2).shape

torch.Size([2, 2, 2, 2])

* stack con `dim = 3`

In [34]:
torch.stack((tensor1, tensor2), dim = 3)

tensor([[[[ 1,  9],
          [ 2, 10]],

         [[ 3, 11],
          [ 4, 12]]],


        [[[ 5, 13],
          [ 6, 14]],

         [[ 7, 15],
          [ 8, 16]]]])

In [35]:
torch.stack((tensor1, tensor2), dim = 3).shape

torch.Size([2, 2, 2, 2])

## VStack Tensors

El método `torch.vstack()` concatena 2 tensores donde cada tensor input es una fila del nuevo tensor

Revisar documentación: https://pytorch.org/docs/stable/generated/torch.vstack.html

In [36]:
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

torch.vstack((vector1, vector2))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
matriz1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

matriz2 = torch.tensor([[7, 8, 9],
                        [10, 11, 12]])

torch.vstack(matriz1, matriz2)

TypeError: vstack() takes 1 positional argument but 2 were given

Este método solo es para vectores, no sirve con matrices o tensores 3D en adelante

## HStack Tensos

`torch.hstack()` concatena vectores en una sola fila, donde cada elemento de los tensores inputs son columnas

Documentación: https://pytorch.org/docs/stable/generated/torch.hstack.html

In [40]:
vector1 = torch.tensor([1, 2, 3])
vector2 = torch.tensor([4, 5, 6])

torch.hstack((vector1, vector2))

tensor([1, 2, 3, 4, 5, 6])

In [41]:
matriz1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

matriz2 = torch.tensor([[7, 8, 9],
                        [10, 11, 12]])

torch.hstack(matriz1, matriz2)

TypeError: hstack() takes 1 positional argument but 2 were given

Como se mencionó anteriormente, `torch.hstack()` solo sirve con vectores y no es aplicables a tensores de mayor orden

## Squeeze Tensors

El método `A.squeeze()` o `torch.squeeze(A)` para un tensor A, elimina las dimensiones unidimensionales de nuestro tensor original

Podemos dar un parámetro `dim` para seleccionar las dimensiones unidimensionales específicas que queremos remover

El parámetro `dim` acepta tuplas conteniendo las dimensiones unidimensionales deseadas a remover, sin embargo, éstas deben ser consecutivas

Documentación: https://pytorch.org/docs/stable/generated/torch.squeeze.html

A continuación veremos algunos ejemplos:

1) 

In [88]:
x = torch.arange(0, 10)
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

In [91]:
x = x.reshape(1, 10)
x, x.shape

(tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 10]))

In [92]:
x = x.squeeze()
x, x.shape

(tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([10]))

Al utilizar `.squeeze()` en este caso, remueve la dimensión extra añadida durante el `.reshape()`

Pasando de una `shape` [1, 10] a [10]

2) 

In [97]:
x = torch.arange(0, 10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
x = x.reshape(2, 5)
x, x.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Size([2, 5]))

In [101]:
x = x.squeeze()
x, x.shape

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 torch.Size([2, 5]))

Para este tensor, debido a que los elementos están repartidos en un arreglo matricial de 2 x 5, no hay dimensiones unidimensionales, por lo que el resultado es el mismo

3. 

In [199]:
x = torch.zeros(2, 3, 6)
x, x.shape

(tensor([[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 3, 6]))

In [200]:
x = x.squeeze()
x, x.shape

(tensor([[[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]],
 
         [[0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0., 0.]]]),
 torch.Size([2, 3, 6]))

De nuevo, no existen dimensiones unidimensionales, por lo que el tensor se mantiene igual

Ahora veremos ejemplos implementando `dim`

1. Sea un vector:

In [205]:
x = torch.zeros(1, 3)
x, x.shape

(tensor([[0., 0., 0.]]), torch.Size([1, 3]))

In [203]:
y = torch.squeeze(x, 0)
y, y.shape

(tensor([0., 0., 0.]), torch.Size([3]))

In [206]:
y = torch.squeeze(x, 1)
y, y.shape

(tensor([[0., 0., 0.]]), torch.Size([1, 3]))

2. Sea un tensor 5D:

In [135]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [132]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [133]:
x = x.squeeze()
x

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [134]:
x.shape

torch.Size([2, 2, 2])

Se remueven todas las dimensiones unitarias si no se especifíca el parámetro `dim`

* `dim = 0`

In [171]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [172]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [173]:
x = x.squeeze(0)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [174]:
x.shape

torch.Size([2, 1, 2, 1, 2])

Debido a que la dimensión 0 no es unitaria, no cambia

* `dim = 1`

In [144]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [141]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [142]:
x = x.squeeze(1)
x

tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [143]:
x.shape

torch.Size([2, 2, 1, 2])

Al indicar `dim = 1` se elimina específicamente la dimensión 1 si ésta es unitaria

**Recordando que las dimensiones se cuentan desde 0 hasta D-1**

* `dim = 2`

In [167]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [168]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [169]:
x = x.squeeze(dim=2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [170]:
x.shape

torch.Size([2, 1, 2, 1, 2])

Debido a que la dimensión 2 no es unitaria, no hay cambio

* `dim = 3`

In [175]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [176]:
x.shape

torch.Size([2, 1, 2, 1, 2])

In [177]:
x = x.squeeze(3)
x

tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])

In [178]:
x.shape

torch.Size([2, 1, 2, 2])

Y así nos podemos ir una por una con cada dimensión

También podemos dar a `dim` una tupla conteniendo las dimensiones unidimensionales que queremos removidas del tensor

3. Sea un tensor 6D:

In [54]:
x = torch.zeros(1, 2, 1, 2, 1, 2)
x

tensor([[[[[[0., 0.]],

           [[0., 0.]]]],



         [[[[0., 0.]],

           [[0., 0.]]]]]])

In [55]:
x.shape

torch.Size([1, 2, 1, 2, 1, 2])

In [56]:
x = x.squeeze((0, 4))
x

tensor([[[[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]]]])

In [57]:
x.shape

torch.Size([2, 1, 2, 2])

En este ejemplo se decidió eliminar las dimensiones 0 y 2

## Unsqueeze Tensors

Para un tensor A, `A.unsqueeze()` o `torch.unsqueeze(A)` añaden una dimensión unidimensional a nuestro tensor original

Para ello debemos especificar el índice donde deseamos la nueva dimensión haciendo uso del parámetro `dim`

Documentación: https://pytorch.org/docs/stable/generated/torch.unsqueeze.html

A continuación veremos ejemplos:

1. Para un vector:

* `dim = 0`

In [71]:
x = torch.tensor([1, 2, 3, 4])
x, x.shape

(tensor([1, 2, 3, 4]), torch.Size([4]))

In [72]:
x = torch.unsqueeze(x, 0)
x, x.shape

(tensor([[1, 2, 3, 4]]), torch.Size([1, 4]))

* `dim = 1`

In [73]:
x = torch.tensor([1, 2, 3, 4])
x, x.shape

(tensor([1, 2, 3, 4]), torch.Size([4]))

In [74]:
x = torch.unsqueeze(x, 1)
x, x.shape

(tensor([[1],
         [2],
         [3],
         [4]]),
 torch.Size([4, 1]))

2. Para una matriz:

* `dim = 0`

In [84]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [85]:
x.shape

torch.Size([2, 3])

In [86]:
x = torch.unsqueeze(x, 0)
x

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [87]:
x.shape

torch.Size([1, 2, 3])

* `dim = 1`

In [88]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [89]:
x.shape

torch.Size([2, 3])

In [90]:
x = x.unsqueeze(1)
x

tensor([[[0., 0., 0.]],

        [[0., 0., 0.]]])

In [91]:
x.shape

torch.Size([2, 1, 3])

* `dim = 2`

In [92]:
x = torch.zeros(2, 3)
x

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [93]:
x.shape

torch.Size([2, 3])

In [94]:
x = x.unsqueeze(2)
x

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])

In [95]:
x.shape

torch.Size([2, 3, 1])

## Permute Tensors

`torch.permute()` regrese una vista de un tensor original reorganizando sus dimensiones de la forma especificada

Para ello se debe entregar una tupla conteniendo el orden de las dimensiones deseado con el parámetro `dims`

Documentación: https://pytorch.org/docs/stable/generated/torch.permute.html

A continuación veremos algunos ejemplos:

1.

In [101]:
x = torch.rand(2, 3, 5)
x

tensor([[[0.6895, 0.6578, 0.0599, 0.0166, 0.5993],
         [0.6353, 0.7915, 0.7936, 0.0769, 0.8988],
         [0.1308, 0.2763, 0.4817, 0.5475, 0.9992]],

        [[0.9155, 0.8512, 0.2215, 0.0804, 0.0846],
         [0.2294, 0.9126, 0.3621, 0.1139, 0.2649],
         [0.3947, 0.3577, 0.8637, 0.4855, 0.3202]]])

In [102]:
x.size()

torch.Size([2, 3, 5])

In [103]:
x = torch.permute(x, (2, 0, 1))
x

tensor([[[0.6895, 0.6353, 0.1308],
         [0.9155, 0.2294, 0.3947]],

        [[0.6578, 0.7915, 0.2763],
         [0.8512, 0.9126, 0.3577]],

        [[0.0599, 0.7936, 0.4817],
         [0.2215, 0.3621, 0.8637]],

        [[0.0166, 0.0769, 0.5475],
         [0.0804, 0.1139, 0.4855]],

        [[0.5993, 0.8988, 0.9992],
         [0.0846, 0.2649, 0.3202]]])

In [104]:
x.shape

torch.Size([5, 2, 3])

2.

Sea un tensor x que contiene la información codificada de una imagen

In [115]:
imagen = torch.rand(size=(224, 224, 3))
imagen.shape

torch.Size([224, 224, 3])

La 1ra dimensión denota la altura de la imagen, la 2da el ancho y la 3ra los canales de color

Podemos cambiar el orden de la forma: (canales de color, altura, ancho)

In [116]:
imagen_permutada = imagen.permute(2, 0, 1)
imagen_permutada.shape

torch.Size([3, 224, 224])

En este ejemplo las dimensiónes cambian de la siguiente forma:

* Dimensión 0 -> Dimensión 1
* Dimensión 1 -> Dimensión 2
* Dimensión 2 -> Dimensión 0

Debido a que `.permute` es una vista **comparten la misma memoria**

Esto se mostrará en el siguiente ejemplo:

3.

In [124]:
x = torch.zeros(2, 3, 4)
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [125]:
x.shape

torch.Size([2, 3, 4])

In [126]:
x_permutada = x.permute(1, 2, 0)
x_permutada

tensor([[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [127]:
x_permutada.shape

torch.Size([3, 4, 2])

In [131]:
x[0][0][0] = 7

In [132]:
x

tensor([[[7., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [133]:
x_permutada

tensor([[[7., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

In [134]:
x_permutada[0][0][1] = 3

In [135]:
x

tensor([[[7., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[3., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [136]:
x_permutada

tensor([[[7., 3.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]])

Debido a que comparten memoria, al modifica alguno se refleja el cambio en ambos