# Selecting Data from Tensors (Indexing)

Indexar (Indexing) con PyTorch es similar a indexar con NumPy

In [1]:
import torch

In [7]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [8]:
x.shape

torch.Size([1, 3, 3])

Para acceder a la 1ra capa de profundidad de nuestro tensor:

In [3]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

Para acceder a la 1ra fila de la 1ra capa de profundidad del tensor:

In [4]:
x[0][0]

tensor([1, 2, 3])

Accediendo al 3er elemento de la 1ra fila de la 1ra capa de profundidad del tensor:

In [6]:
x[0][0][2]

tensor(3)

Por ejemplo, para acceder al número 8 dentro de nuestro tensor:

In [9]:
x[0][2][1]

tensor(8)

También se puede utilizar `:` para seleccionar todos los elementos de cierta dimensión

Por ejemplo:

1. Seleccionar todos los elementos de la 2da fila

In [10]:
x[0][1][:]

tensor([4, 5, 6])

De esta forma, se seleccionan todos los elementos de la 2da fila

2. Seleccionar todos los elementos de las dimensiones 0 y 1 pero solo indexar un elemento de la 2da dimensión

In [19]:
x[:, :, 1]

tensor([[2, 5, 8]])

En este caso se toman de todas las capas y filas, los elementos de la 2da columna

3. Seleccionar todos los valores de la dimensión 0 pero solo los de índice 1 de la 1ra y segunda dimensión

In [21]:
x[:,1, 1]

tensor([5])

En este caso se selecciona los elementos de todas las capas que se encuentran en la 2da fila y columna 

Es una forma de seleccionar los elementos de en medio dentro de todas las capas de profundidad

4. Seleccionar los elementos de índice 0 de la dimensión 0-1 y todos los elementos de la 2da dimensión

In [22]:
x[0, 0, :]

tensor([1, 2, 3])

De esta forma se seleccionan los elementos de la primera fila en la primera capa

Ejercicios:

1. Regresar el 9

In [23]:
x[0][2][2]

tensor(9)

2. Regresar 3, 6 y 9

In [24]:
x[0, :, 2]

tensor([3, 6, 9])

3. Obtener los elementos de la diagonal

* Metodo 1: Usando Indexing

In [27]:
indices = torch.arange(x.size(1))
indices

tensor([0, 1, 2])

In [28]:
diagonal = x[0, indices, indices]
diagonal

tensor([1, 5, 9])

Método 2: Usando `squeeze` y `diag`

Ya existe un método para obtener la diagonal de una matriz (tensor 2D) llamado `torch.diag()`

Documentación: https://pytorch.org/docs/stable/generated/torch.diag.html

Para ello debemos primero convertir nuestro tensor 3D en 2D

In [31]:
x_modificada = x.squeeze()
x_modificada, x_modificada.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [32]:
diagonal = x_modificada.diag()
diagonal

tensor([1, 5, 9])