# PyTorch and Numpy Tensors

Numpy es una biblioteca de computo numérico muy popular de Python. Debido a ello, PyTorch tiene funcionalidad para interactuar con ella

Para hacer transformaciones de tipos de data:

* Data en Numpy -> Tensor en PyTorch: `torch.from_numpy(ndarray)`
* Tensor en PyTorch -> Data en Numpy: `torch.Tensor.numpy()`

## Arreglo de Numpy a Tensor de PyTorch

In [2]:
import torch
import numpy as np

In [5]:
arreglo = np.arange(0., 10.)
arreglo

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [6]:
tns = torch.from_numpy(arreglo)
tns

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)

Cabe mencionar que el tipo de datos de nuestro tensor es float64 debido a que es el tipo de datos de numpy por defecto

In [7]:
arreglo.dtype

dtype('float64')

In [8]:
tns.dtype

torch.float64

Por otro lado, PyTorch por defecto crea sus datos en float32

In [11]:
torch.arange(0., 10.).dtype

torch.float32

Si queremos mantener nuestra convención de PyTorch, se hace de la siguiente forma:

In [12]:
tns = torch.from_numpy(arreglo).type(torch.float32)
tns, tns.dtype

(tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

Es importante mencionar que al utilizar `torch.from_numpy()` se crea un nuevo tensor en memoria, por lo que si se modifica el arreglo de numpy ésto no afectará al tensor creado

In [13]:
arreglo += 1
arreglo 

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [14]:
tns

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Tensor de PyTorch a Arreglo de Numpy

In [18]:
tns = torch.ones(10)
tns, tns.dtype

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), torch.float32)

In [17]:
arreglo = torch.Tensor.numpy(tns)
arreglo

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

Así como al crear un tensor usando `torch.from_numpy()` se hereda el tipo de datos del arreglo de Numpy, al crear un arreglo de Numpy usando `torch.Tensor.numpy()` se heredará el tipo de datos de nuestro tensor

Los tipos de datos por defecto son:

* Numpy - float64
* PyTorch - float32

Al modificar el tensor usado para crear el arreglo, ésto solo afectará el tensor

Ambos tienen distinta dirección de memoria asignada

In [19]:
tns += 1
tns

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [20]:
arreglo

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)