# Reproducibility

Documentación: https://pytorch.org/docs/stable/notes/randomness.html

In [1]:
import torch

De forma simplificada, una red neuronal aprende de la siguiente forma:

Iniciar con datos rand -> operaciones tensoriales -> actualizar datos rand para representar mejor la data -> repetir

Sin embargo, a veces queremos crear experimentos y resultados que sean reproducibles por otros equipos de trabajo

Al hacer uso de `torch.rand()` cada que se corra el código los números cambiarán aleatoriamente

In [2]:
torch.rand(2, 3)

tensor([[0.7823, 0.2437, 0.4038],
        [0.1832, 0.5828, 0.9855]])

In [3]:
rand_A = torch.rand(3, 4)
rand_B = torch.rand(3, 4)

rand_A == rand_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

## Random Seed

Para reducir la aleatoriedad en redes neuronales y PyTorch, se hace uso del concepto de **random seed**

"Lo que hace una random seed es 'darle sabor' a nuestra aleatoriedad"

Debido a que las computadoras son deterministas, no existe una verdadera aleatoriedad por lo que podemos tomar esto a nuestro favor con **random seed**

"En términos de programación y matemáticas, una semilla (seed) es un valor inicial utilizado para generar números pseudo-aleatorios"

El valor 42 es un valor popular para este parámetro debido a su mención en la serie de libros de ciencia ficción "The Hitchhiker's Guide to the Galaxy"

## Tensores Random pero Reproducibles

A continuación crearemos tensores aleatorios pero reproducibles:

In [4]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

In [5]:
rand_C = torch.rand(3, 4)
rand_D = torch.rand(3, 4)

rand_C == rand_D

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Para que funcione debemos de llamar a la semilla cada que se crea un tensor aleatorio

In [6]:
torch.manual_seed(RANDOM_SEED)
rand_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
rand_D = torch.rand(3, 4)

rand_C == rand_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])