# Exercices and Extra-Curriculum

## Exercices

In [47]:
import torch

Para terminar con la unidad 1 "Fundamentos de PyTorch" hay que realizar algunos ejercicios de práctica

Hay que apoyarse en las notas de clase y el repositorio de GitHub:

* Notas de Clase: https://www.learnpytorch.io/
* Repositorio de GitHub: https://github.com/mrdbourke/pytorch-deep-learning

Los ejercicios de esta 1ra unidad se encuentran en el siguiente enlace: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

1. Leer la documentación de torch.Tensor y torch.cuda:

* torch.Tensor: https://pytorch.org/docs/stable/tensors.html
* torch.cuda: https://pytorch.org/docs/stable/cuda.html

2. Crear un tensor aleatorio con shape (7, 7)

In [48]:
x = torch.rand(7, 7)
x

tensor([[0.6511, 0.7745, 0.4369, 0.5191, 0.6159, 0.8102, 0.9801],
        [0.1147, 0.3168, 0.6965, 0.9143, 0.9351, 0.9412, 0.5995],
        [0.0652, 0.5460, 0.1872, 0.0340, 0.9442, 0.8802, 0.0012],
        [0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038, 0.6833],
        [0.7529, 0.8579, 0.6870, 0.0051, 0.1757, 0.7497, 0.6047],
        [0.1100, 0.2121, 0.9704, 0.8369, 0.2820, 0.3742, 0.0237],
        [0.4910, 0.1235, 0.1143, 0.4725, 0.5751, 0.2952, 0.7967]])

3. Realiza una multiplicación matricial con otro tensor de shape (1, 7) 

In [49]:
y = torch.rand(1, 7)
y

tensor([[0.1957, 0.9537, 0.8426, 0.0784, 0.3756, 0.5226, 0.5730]])

In [50]:
xy = torch.matmul(x, y.T)
xy

tensor([[2.4911],
        [2.1696],
        [1.5092],
        [1.6439],
        [2.3490],
        [1.4221],
        [1.1739]])

4. Establecer la semilla aleatoria a 0 y repetir los ejercicios 2) y 3)

In [51]:
RANDOM_SEED = 0

In [52]:
torch.manual_seed(RANDOM_SEED)
x = torch.rand(7, 7)
x

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

In [53]:
torch.manual_seed(RANDOM_SEED)
y = torch.rand(1, 7)
y

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

In [54]:
xy = torch.matmul(x, y.T)
xy

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

5. Establecer la semilla aleatoria a 1234 en el GPU. Revisar la documentación de CUDA: https://pytorch.org/docs/stable/cuda.html

En concreto, se utiliza el método documentado a continuación: https://pytorch.org/docs/stable/generated/torch.cuda.manual_seed.html#torch.cuda.manual_seed

In [59]:
torch.cuda.manual_seed(1234)

6. Crear 2 tensores aleatorios de shape (2, 3) y mandarlos al GPU, usando la semilla 1234

In [62]:
torch.manual_seed(1234)
x = torch.rand(2, 3)
x_gpu = x.to(device="cuda")
x_gpu

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

In [63]:
torch.manual_seed(1234)
y = torch.rand(2, 3)
y_gpu = y.to(device="cuda")
y_gpu

tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')

7. Realizar una multiplicación matricial en los tensores creados en el ejercicio 6)

In [64]:
xy_gpu = torch.matmul(x_gpu, y_gpu.T)
xy_gpu

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]], device='cuda:0')

8. Encuentra el máximo y mínimo en el output del 7)

In [66]:
xy_gpu.min(), xy_gpu.max()

(tensor(0.2161, device='cuda:0'), tensor(0.6287, device='cuda:0'))

9. Encontrar los índices del mínimo y máximo del output del ejercicio 7)

In [67]:
xy_gpu.argmin(), xy_gpu.argmax()

(tensor(1, device='cuda:0'), tensor(3, device='cuda:0'))

10. Crear un tensor aleatorio con shape (1, 1, 1, 10) y uno con sus dimensiones unidimensionales removidas; teniendo la semilla aleatoria en 7. Imprimir el los tensores con sus shapes correspondientes

In [68]:
torch.manual_seed(7)
x = torch.rand(1, 1, 1, 10)
x, x.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [69]:
y = x.squeeze()
y, y.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))

## Extra-Curriculum

Del tutorial de básicos de PyTorch: https://pytorch.org/tutorials/beginner/basics/intro.html

Estudiar las secciones:

* Quickstart: https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html

* Tensors: https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html